name: CI Pipeline  # Name your workflow

on:
  push:  # Trigger the workflow on push events
    branches: [main]  # Specify the branches to trigger on

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the runner environment

    steps:
      - uses: actions/checkout@v3  # Checkout the repository code
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Run tests
        run: npm run test
      - name: Build
        run: npm run build
